// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticleM = "article"

// ArticleM mapped from table <article>
type ArticleM struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                   // 内部主键ID（自增序列）
	ArticleID   string         `gorm:"column:article_id;not null;default:gen_random_uuid();comment:文章业务唯一UUID" json:"articleId"` // 文章业务唯一UUID
	TaskID      string         `gorm:"column:task_id;not null;comment:所属任务UUID（外键）" json:"taskId"`                               // 所属任务UUID（外键）
	TaskBrandID string         `gorm:"column:task_brand_id;not null;comment:所属任务品牌关联UUID（外键）" json:"taskBrandId"`                // 所属任务品牌关联UUID（外键）
	BlockID     string         `gorm:"column:block_id;not null;comment:证据块UUID（外键）" json:"blockId"`                              // 证据块UUID（外键）
	Title       string         `gorm:"column:title;not null;comment:文章标题" json:"title"`                                          // 文章标题
	ContentMd   string         `gorm:"column:content_md;not null;comment:文章内容（Markdown格式）" json:"contentMd"`                     // 文章内容（Markdown格式）
	Status      string         `gorm:"column:status;not null;default:generated;comment:文章状态（ENUM）" json:"status"`                // 文章状态（ENUM）
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`       // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`       // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                               // 软删除时间（NULL=未删除）
}

// TableName ArticleM's table name
func (*ArticleM) TableName() string {
	return TableNameArticleM
}
