// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBrandM = "brand"

// BrandM mapped from table <brand>
type BrandM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`               // 内部主键ID（自增序列）
	BrandID   string         `gorm:"column:brand_id;not null;default:gen_random_uuid();comment:品牌业务唯一UUID" json:"brandId"` // 品牌业务唯一UUID
	UserID    string         `gorm:"column:user_id;not null;comment:所属用户UUID（外键）" json:"userId"`                           // 所属用户UUID（外键）
	Name      string         `gorm:"column:name;not null;comment:品牌名称" json:"name"`                                        // 品牌名称
	Flat      int16          `gorm:"column:flat;not null;default:1;comment:品牌层级标志（1=扁平结构）" json:"flat"`                    // 品牌层级标志（1=扁平结构）
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`   // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`   // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                           // 软删除时间（NULL=未删除）
}

// TableName BrandM's table name
func (*BrandM) TableName() string {
	return TableNameBrandM
}
