// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEvidenceBlockM = "evidence_block"

// EvidenceBlockM mapped from table <evidence_block>
type EvidenceBlockM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`             // 内部主键ID（自增序列）
	EbID      string         `gorm:"column:eb_id;not null;default:gen_random_uuid();comment:证据块业务唯一UUID" json:"ebId"`    // 证据块业务唯一UUID
	Label     string         `gorm:"column:label;not null;comment:证据块标签/名称" json:"label"`                                // 证据块标签/名称
	IsEnabled bool           `gorm:"column:is_enabled;not null;default:true;comment:是否启用" json:"isEnabled"`              // 是否启用
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                         // 软删除时间（NULL=未删除）
}

// TableName EvidenceBlockM's table name
func (*EvidenceBlockM) TableName() string {
	return TableNameEvidenceBlockM
}
