// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMonitorM = "monitor"

// MonitorM mapped from table <monitor>
type MonitorM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`               // 内部主键ID（自增序列）
	ServerName   *string   `gorm:"column:server_name;comment:服务器名称" json:"serverName"`                                   // 服务器名称
	ServerIP     *string   `gorm:"column:server_ip;comment:服务器IP地址" json:"serverIp"`                                     // 服务器IP地址
	CPUUsage     float64   `gorm:"column:cpu_usage;not null;comment:CPU使用率（%）" json:"cpuUsage"`                          // CPU使用率（%）
	CPUCores     *int32    `gorm:"column:cpu_cores;comment:CPU核心数" json:"cpuCores"`                                      // CPU核心数
	MemoryUsage  float64   `gorm:"column:memory_usage;not null;comment:内存使用率（%）" json:"memoryUsage"`                     // 内存使用率（%）
	MemoryTotal  *int64    `gorm:"column:memory_total;comment:总内存（字节）" json:"memoryTotal"`                               // 总内存（字节）
	MemoryUsed   *int64    `gorm:"column:memory_used;comment:已用内存（字节）" json:"memoryUsed"`                                // 已用内存（字节）
	DiskUsage    float64   `gorm:"column:disk_usage;not null;comment:磁盘使用率（%）" json:"diskUsage"`                         // 磁盘使用率（%）
	DiskTotal    *int64    `gorm:"column:disk_total;comment:总磁盘空间（字节）" json:"diskTotal"`                                 // 总磁盘空间（字节）
	DiskUsed     *int64    `gorm:"column:disk_used;comment:已用磁盘空间（字节）" json:"diskUsed"`                                  // 已用磁盘空间（字节）
	NetworkRx    *int64    `gorm:"column:network_rx;comment:网络接收字节" json:"networkRx"`                                    // 网络接收字节
	NetworkTx    *int64    `gorm:"column:network_tx;comment:网络发送字节" json:"networkTx"`                                    // 网络发送字节
	LoadAvg1     *float64  `gorm:"column:load_avg_1;comment:1分钟负载平均值" json:"loadAvg1"`                                   // 1分钟负载平均值
	Uptime       *int64    `gorm:"column:uptime;comment:系统运行时间（秒）" json:"uptime"`                                        // 系统运行时间（秒）
	ProcessCount *int32    `gorm:"column:process_count;comment:进程数" json:"processCount"`                                 // 进程数
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:监控记录时间" json:"createdAt"` // 监控记录时间
}

// TableName MonitorM's table name
func (*MonitorM) TableName() string {
	return TableNameMonitorM
}
