// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProjectM = "project"

// ProjectM mapped from table <project>
type ProjectM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                   // 内部主键ID（自增序列）
	ProjectID string         `gorm:"column:project_id;not null;default:gen_random_uuid();comment:项目业务唯一UUID" json:"projectId"` // 项目业务唯一UUID
	Name      string         `gorm:"column:name;not null;comment:项目名称" json:"name"`                                            // 项目名称
	OwnerID   string         `gorm:"column:owner_id;not null;comment:项目所有者用户UUID（外键）" json:"ownerId"`                          // 项目所有者用户UUID（外键）
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`       // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`       // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                               // 软删除时间（NULL=未删除）
}

// TableName ProjectM's table name
func (*ProjectM) TableName() string {
	return TableNameProjectM
}
