// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTaskM = "task"

// TaskM mapped from table <task>
type TaskM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`             // 内部主键ID（自增序列）
	TaskID    string         `gorm:"column:task_id;not null;default:gen_random_uuid();comment:任务业务唯一UUID" json:"taskId"` // 任务业务唯一UUID
	ProjectID string         `gorm:"column:project_id;not null;comment:所属项目UUID（外键）" json:"projectId"`                   // 所属项目UUID（外键）
	Name      string         `gorm:"column:name;not null;comment:任务名称" json:"name"`                                      // 任务名称
	BrandSeed string         `gorm:"column:brand_seed;not null;comment:品牌种子数据（初始品牌列表，JSON格式）" json:"brandSeed"`          // 品牌种子数据（初始品牌列表，JSON格式）
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                         // 软删除时间（NULL=未删除）
}

// TableName TaskM's table name
func (*TaskM) TableName() string {
	return TableNameTaskM
}
