// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskEvidenceBlockM = "task_evidence_block"

// TaskEvidenceBlockM mapped from table <task_evidence_block>
type TaskEvidenceBlockM struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"` // 内部主键ID（自增序列）
	TaskID  string `gorm:"column:task_id;not null;comment:任务UUID（外键）" json:"taskId"`               // 任务UUID（外键）
	BlockID string `gorm:"column:block_id;not null;comment:证据块UUID（外键）" json:"blockId"`            // 证据块UUID（外键）
}

// TableName TaskEvidenceBlockM's table name
func (*TaskEvidenceBlockM) TableName() string {
	return TableNameTaskEvidenceBlockM
}
