// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTaskBrandM = "task_brand"

// TaskBrandM mapped from table <task_brand>
type TaskBrandM struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                            // 内部主键ID（自增序列）
	TaskBrandID string         `gorm:"column:task_brand_id;not null;default:gen_random_uuid();comment:任务品牌关联业务唯一UUID" json:"taskBrandId"` // 任务品牌关联业务唯一UUID
	TaskID      string         `gorm:"column:task_id;not null;comment:任务UUID（外键）" json:"taskId"`                                          // 任务UUID（外键）
	BrandID     string         `gorm:"column:brand_id;not null;comment:品牌UUID（外键）" json:"brandId"`                                        // 品牌UUID（外键）
	Name        string         `gorm:"column:name;not null;comment:关联品牌名称（冗余存储）" json:"name"`                                             // 关联品牌名称（冗余存储）
	IsSeed      bool           `gorm:"column:is_seed;not null;comment:是否为种子品牌" json:"isSeed"`                                             // 是否为种子品牌
	SortOrder   int32          `gorm:"column:sort_order;not null;comment:排序序号" json:"sortOrder"`                                          // 排序序号
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`                // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`                // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                                        // 软删除时间（NULL=未删除）
}

// TableName TaskBrandM's table name
func (*TaskBrandM) TableName() string {
	return TableNameTaskBrandM
}
