// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/apiserver.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apiserver_v1_apiserver_proto protoreflect.FileDescriptor

const file_apiserver_v1_apiserver_proto_rawDesc = "" +
	"\n" +
	"\x1capiserver/v1/apiserver.proto\x12\fapiserver.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1aapiserver/v1/healthz.proto\x1a\x17apiserver/v1/user.proto\x1a\x17apiserver/v1/menu.proto\x1a\x1dapiserver/v1/permission.proto\x1a\x17apiserver/v1/role.proto\x1a\x1capiserver/v1/user_role.proto2\xf5+\n" +
	"\vBlogService\x12\x91\x01\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x1d.apiserver.v1.HealthzResponse\"O\x92A<\n" +
	"\f服务治理\x12\f健康检查\x1a\x1e检查服务是否健康运行\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12\xac\x01\n" +
	"\x05Login\x12\x1a.apiserver.v1.LoginRequest\x1a\x1b.apiserver.v1.LoginResponse\"j\x92AN\n" +
	"\f用户认证\x12\f用户登录\x1a0用户使用用户名和密码进行登录认证\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12\xc9\x01\n" +
	"\fRefreshToken\x12!.apiserver.v1.RefreshTokenRequest\x1a\".apiserver.v1.RefreshTokenResponse\"r\x92AN\n" +
	"\f用户认证\x12\f刷新令牌\x1a0使用现有令牌刷新获取新的访问令牌\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/auth/refresh-token\x12\x9e\x01\n" +
	"\n" +
	"CreateUser\x12\x1f.apiserver.v1.CreateUserRequest\x1a .apiserver.v1.CreateUserResponse\"M\x92A6\n" +
	"\f用户管理\x12\f创建用户\x1a\x18创建一个新的用户\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\xa5\x01\n" +
	"\aGetUser\x12\x1c.apiserver.v1.GetUserRequest\x1a\x1d.apiserver.v1.GetUserResponse\"]\x92A@\n" +
	"\f用户管理\x12\f获取用户\x1a\"根据用户 ID 获取用户信息\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users/{userID}\x12\xb1\x01\n" +
	"\n" +
	"UpdateUser\x12\x1f.apiserver.v1.UpdateUserRequest\x1a .apiserver.v1.UpdateUserResponse\"`\x92A@\n" +
	"\f用户管理\x12\f更新用户\x1a\"根据用户 ID 更新用户信息\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/users/{userID}\x12\xa8\x01\n" +
	"\n" +
	"DeleteUser\x12\x1f.apiserver.v1.DeleteUserRequest\x1a .apiserver.v1.DeleteUserResponse\"W\x92A:\n" +
	"\f用户管理\x12\f删除用户\x1a\x1c根据用户 ID 删除用户\x82\xd3\xe4\x93\x02\x14*\x12/v1/users/{userID}\x12\x99\x01\n" +
	"\tListUsers\x12\x1d.apiserver.v1.ListUserRequest\x1a\x1e.apiserver.v1.ListUserResponse\"M\x92A9\n" +
	"\f用户管理\x12\f列表用户\x1a\x1b获取所有用户的列表\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x9e\x01\n" +
	"\n" +
	"CreateMenu\x12\x1f.apiserver.v1.CreateMenuRequest\x1a .apiserver.v1.CreateMenuResponse\"M\x92A6\n" +
	"\f菜单管理\x12\f创建菜单\x1a\x18创建一个新的菜单\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/menus\x12\xa5\x01\n" +
	"\aGetMenu\x12\x1c.apiserver.v1.GetMenuRequest\x1a\x1d.apiserver.v1.GetMenuResponse\"]\x92A@\n" +
	"\f菜单管理\x12\f获取菜单\x1a\"根据菜单 ID 获取菜单信息\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/menus/{menuID}\x12\xb1\x01\n" +
	"\n" +
	"UpdateMenu\x12\x1f.apiserver.v1.UpdateMenuRequest\x1a .apiserver.v1.UpdateMenuResponse\"`\x92A@\n" +
	"\f菜单管理\x12\f更新菜单\x1a\"根据菜单 ID 更新菜单信息\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/menus/{menuID}\x12\xa8\x01\n" +
	"\n" +
	"DeleteMenu\x12\x1f.apiserver.v1.DeleteMenuRequest\x1a .apiserver.v1.DeleteMenuResponse\"W\x92A:\n" +
	"\f菜单管理\x12\f删除菜单\x1a\x1c根据菜单 ID 删除菜单\x82\xd3\xe4\x93\x02\x14*\x12/v1/menus/{menuID}\x12\x90\x01\n" +
	"\tListMenus\x12\x1d.apiserver.v1.ListMenuRequest\x1a\x1e.apiserver.v1.ListMenuResponse\"D\x92A0\n" +
	"\f菜单管理\x12\f列表菜单\x1a\x12获取菜单列表\x82\xd3\xe4\x93\x02\v\x12\t/v1/menus\x12\xa6\x01\n" +
	"\fListMenuTree\x12!.apiserver.v1.ListMenuTreeRequest\x1a\".apiserver.v1.ListMenuTreeResponse\"O\x92A6\n" +
	"\f菜单管理\x12\x0f列表菜单树\x1a\x15获取菜单树结构\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/menus/tree\x12\xc3\x01\n" +
	"\x0fGetUserMenuTree\x12$.apiserver.v1.GetUserMenuTreeRequest\x1a%.apiserver.v1.GetUserMenuTreeResponse\"c\x92AE\n" +
	"\f菜单管理\x12\x15获取用户菜单树\x1a\x1e获取当前用户的菜单树\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/menu-tree\x12\xb6\x01\n" +
	"\x10CreatePermission\x12%.apiserver.v1.CreatePermissionRequest\x1a&.apiserver.v1.CreatePermissionResponse\"S\x92A6\n" +
	"\f权限管理\x12\f创建权限\x1a\x18创建一个新的权限\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/permissions\x12\xc3\x01\n" +
	"\rGetPermission\x12\".apiserver.v1.GetPermissionRequest\x1a#.apiserver.v1.GetPermissionResponse\"i\x92A@\n" +
	"\f权限管理\x12\f获取权限\x1a\"根据权限 ID 获取权限信息\x82\xd3\xe4\x93\x02 \x12\x1e/v1/permissions/{permissionID}\x12\xcf\x01\n" +
	"\x10UpdatePermission\x12%.apiserver.v1.UpdatePermissionRequest\x1a&.apiserver.v1.UpdatePermissionResponse\"l\x92A@\n" +
	"\f权限管理\x12\f更新权限\x1a\"根据权限 ID 更新权限信息\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/permissions/{permissionID}\x12\xc6\x01\n" +
	"\x10DeletePermission\x12%.apiserver.v1.DeletePermissionRequest\x1a&.apiserver.v1.DeletePermissionResponse\"c\x92A:\n" +
	"\f权限管理\x12\f删除权限\x1a\x1c根据权限 ID 删除权限\x82\xd3\xe4\x93\x02 *\x1e/v1/permissions/{permissionID}\x12\xa8\x01\n" +
	"\x0fListPermissions\x12#.apiserver.v1.ListPermissionRequest\x1a$.apiserver.v1.ListPermissionResponse\"J\x92A0\n" +
	"\f权限管理\x12\f列表权限\x1a\x12获取权限列表\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/permissions\x12\xbe\x01\n" +
	"\x12ListPermissionTree\x12'.apiserver.v1.ListPermissionTreeRequest\x1a(.apiserver.v1.ListPermissionTreeResponse\"U\x92A6\n" +
	"\f权限管理\x12\x0f列表权限树\x1a\x15获取权限树结构\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/permissions/tree\x12\x9e\x01\n" +
	"\n" +
	"CreateRole\x12\x1f.apiserver.v1.CreateRoleRequest\x1a .apiserver.v1.CreateRoleResponse\"M\x92A6\n" +
	"\f角色管理\x12\f创建角色\x1a\x18创建一个新的角色\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/roles\x12\xa5\x01\n" +
	"\aGetRole\x12\x1c.apiserver.v1.GetRoleRequest\x1a\x1d.apiserver.v1.GetRoleResponse\"]\x92A@\n" +
	"\f角色管理\x12\f获取角色\x1a\"根据角色 ID 获取角色信息\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/roles/{roleID}\x12\xb1\x01\n" +
	"\n" +
	"UpdateRole\x12\x1f.apiserver.v1.UpdateRoleRequest\x1a .apiserver.v1.UpdateRoleResponse\"`\x92A@\n" +
	"\f角色管理\x12\f更新角色\x1a\"根据角色 ID 更新角色信息\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/roles/{roleID}\x12\xa8\x01\n" +
	"\n" +
	"DeleteRole\x12\x1f.apiserver.v1.DeleteRoleRequest\x1a .apiserver.v1.DeleteRoleResponse\"W\x92A:\n" +
	"\f角色管理\x12\f删除角色\x1a\x1c根据角色 ID 删除角色\x82\xd3\xe4\x93\x02\x14*\x12/v1/roles/{roleID}\x12\x90\x01\n" +
	"\tListRoles\x12\x1d.apiserver.v1.ListRoleRequest\x1a\x1e.apiserver.v1.ListRoleResponse\"D\x92A0\n" +
	"\f角色管理\x12\f列表角色\x1a\x12获取角色列表\x82\xd3\xe4\x93\x02\v\x12\t/v1/roles\x12\xe9\x01\n" +
	"\x17AssignPermissionsToRole\x12,.apiserver.v1.AssignPermissionsToRoleRequest\x1a-.apiserver.v1.AssignPermissionsToRoleResponse\"q\x92AE\n" +
	"\f角色管理\x12\x15给角色分配权限\x1a\x1e为角色分配或更新权限\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/roles/{roleID}/permissions\x12\xd1\x01\n" +
	"\x12GetRolePermissions\x12'.apiserver.v1.GetRolePermissionsRequest\x1a(.apiserver.v1.GetRolePermissionsResponse\"h\x92A?\n" +
	"\f角色管理\x12\x12获取角色权限\x1a\x1b获取角色的权限列表\x82\xd3\xe4\x93\x02 \x12\x1e/v1/roles/{roleID}/permissions\x12\xc8\x01\n" +
	"\x11AssignRolesToUser\x12&.apiserver.v1.AssignRolesToUserRequest\x1a'.apiserver.v1.AssignRolesToUserResponse\"b\x92A<\n" +
	"\f用户管理\x12\x15给用户分配角色\x1a\x15为用户分配角色\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/users/{userID}/roles\x12\xc2\x01\n" +
	"\fGetUserRoles\x12!.apiserver.v1.GetUserRolesRequest\x1a\".apiserver.v1.GetUserRolesResponse\"k\x92AH\n" +
	"\f用户管理\x12\x12获取用户角色\x1a$获取用户的角色列表和权限\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/users/{userID}/roles\x12\xd7\x01\n" +
	"\x12RemoveRoleFromUser\x12'.apiserver.v1.RemoveRoleFromUserRequest\x1a(.apiserver.v1.RemoveRoleFromUserResponse\"n\x92AB\n" +
	"\f用户管理\x12\x15从用户移除角色\x1a\x1b从用户移除指定角色\x82\xd3\xe4\x93\x02#*!/v1/users/{userID}/roles/{roleID}B\x8a\x05\x92A\xc5\x04\x12\x9a\x04\n" +
	"\x13Blog Service API v1\x12\x8f\x03Blog 服务提供文章、分类、标签、评论、用户等模块的 RESTful API：\n" +
	"- 用户认证与权限控制\n" +
	"- 文章发布、编辑、删除、草稿与置顶\n" +
	"- 分类与标签管理（创建、修改、归类）\n" +
	"- 评论与回复、点赞与收藏\n" +
	"- 搜索与筛选（按作者、标签、时间范围）\n" +
	"- 附件/图片上传与资源管理\n" +
	"- 通知与订阅\n" +
	"- 管理后台与审计日志\"l\n" +
	"\x1egin-enterprise-template 项目\x122https://github.com/clin211/gin-enterprise-template\x1a\x16767425412lin@gmail.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ?github.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1b\x06proto3"

var file_apiserver_v1_apiserver_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                   // 0: google.protobuf.Empty
	(*LoginRequest)(nil),                    // 1: apiserver.v1.LoginRequest
	(*RefreshTokenRequest)(nil),             // 2: apiserver.v1.RefreshTokenRequest
	(*CreateUserRequest)(nil),               // 3: apiserver.v1.CreateUserRequest
	(*GetUserRequest)(nil),                  // 4: apiserver.v1.GetUserRequest
	(*UpdateUserRequest)(nil),               // 5: apiserver.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),               // 6: apiserver.v1.DeleteUserRequest
	(*ListUserRequest)(nil),                 // 7: apiserver.v1.ListUserRequest
	(*CreateMenuRequest)(nil),               // 8: apiserver.v1.CreateMenuRequest
	(*GetMenuRequest)(nil),                  // 9: apiserver.v1.GetMenuRequest
	(*UpdateMenuRequest)(nil),               // 10: apiserver.v1.UpdateMenuRequest
	(*DeleteMenuRequest)(nil),               // 11: apiserver.v1.DeleteMenuRequest
	(*ListMenuRequest)(nil),                 // 12: apiserver.v1.ListMenuRequest
	(*ListMenuTreeRequest)(nil),             // 13: apiserver.v1.ListMenuTreeRequest
	(*GetUserMenuTreeRequest)(nil),          // 14: apiserver.v1.GetUserMenuTreeRequest
	(*CreatePermissionRequest)(nil),         // 15: apiserver.v1.CreatePermissionRequest
	(*GetPermissionRequest)(nil),            // 16: apiserver.v1.GetPermissionRequest
	(*UpdatePermissionRequest)(nil),         // 17: apiserver.v1.UpdatePermissionRequest
	(*DeletePermissionRequest)(nil),         // 18: apiserver.v1.DeletePermissionRequest
	(*ListPermissionRequest)(nil),           // 19: apiserver.v1.ListPermissionRequest
	(*ListPermissionTreeRequest)(nil),       // 20: apiserver.v1.ListPermissionTreeRequest
	(*CreateRoleRequest)(nil),               // 21: apiserver.v1.CreateRoleRequest
	(*GetRoleRequest)(nil),                  // 22: apiserver.v1.GetRoleRequest
	(*UpdateRoleRequest)(nil),               // 23: apiserver.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),               // 24: apiserver.v1.DeleteRoleRequest
	(*ListRoleRequest)(nil),                 // 25: apiserver.v1.ListRoleRequest
	(*AssignPermissionsToRoleRequest)(nil),  // 26: apiserver.v1.AssignPermissionsToRoleRequest
	(*GetRolePermissionsRequest)(nil),       // 27: apiserver.v1.GetRolePermissionsRequest
	(*AssignRolesToUserRequest)(nil),        // 28: apiserver.v1.AssignRolesToUserRequest
	(*GetUserRolesRequest)(nil),             // 29: apiserver.v1.GetUserRolesRequest
	(*RemoveRoleFromUserRequest)(nil),       // 30: apiserver.v1.RemoveRoleFromUserRequest
	(*HealthzResponse)(nil),                 // 31: apiserver.v1.HealthzResponse
	(*LoginResponse)(nil),                   // 32: apiserver.v1.LoginResponse
	(*RefreshTokenResponse)(nil),            // 33: apiserver.v1.RefreshTokenResponse
	(*CreateUserResponse)(nil),              // 34: apiserver.v1.CreateUserResponse
	(*GetUserResponse)(nil),                 // 35: apiserver.v1.GetUserResponse
	(*UpdateUserResponse)(nil),              // 36: apiserver.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),              // 37: apiserver.v1.DeleteUserResponse
	(*ListUserResponse)(nil),                // 38: apiserver.v1.ListUserResponse
	(*CreateMenuResponse)(nil),              // 39: apiserver.v1.CreateMenuResponse
	(*GetMenuResponse)(nil),                 // 40: apiserver.v1.GetMenuResponse
	(*UpdateMenuResponse)(nil),              // 41: apiserver.v1.UpdateMenuResponse
	(*DeleteMenuResponse)(nil),              // 42: apiserver.v1.DeleteMenuResponse
	(*ListMenuResponse)(nil),                // 43: apiserver.v1.ListMenuResponse
	(*ListMenuTreeResponse)(nil),            // 44: apiserver.v1.ListMenuTreeResponse
	(*GetUserMenuTreeResponse)(nil),         // 45: apiserver.v1.GetUserMenuTreeResponse
	(*CreatePermissionResponse)(nil),        // 46: apiserver.v1.CreatePermissionResponse
	(*GetPermissionResponse)(nil),           // 47: apiserver.v1.GetPermissionResponse
	(*UpdatePermissionResponse)(nil),        // 48: apiserver.v1.UpdatePermissionResponse
	(*DeletePermissionResponse)(nil),        // 49: apiserver.v1.DeletePermissionResponse
	(*ListPermissionResponse)(nil),          // 50: apiserver.v1.ListPermissionResponse
	(*ListPermissionTreeResponse)(nil),      // 51: apiserver.v1.ListPermissionTreeResponse
	(*CreateRoleResponse)(nil),              // 52: apiserver.v1.CreateRoleResponse
	(*GetRoleResponse)(nil),                 // 53: apiserver.v1.GetRoleResponse
	(*UpdateRoleResponse)(nil),              // 54: apiserver.v1.UpdateRoleResponse
	(*DeleteRoleResponse)(nil),              // 55: apiserver.v1.DeleteRoleResponse
	(*ListRoleResponse)(nil),                // 56: apiserver.v1.ListRoleResponse
	(*AssignPermissionsToRoleResponse)(nil), // 57: apiserver.v1.AssignPermissionsToRoleResponse
	(*GetRolePermissionsResponse)(nil),      // 58: apiserver.v1.GetRolePermissionsResponse
	(*AssignRolesToUserResponse)(nil),       // 59: apiserver.v1.AssignRolesToUserResponse
	(*GetUserRolesResponse)(nil),            // 60: apiserver.v1.GetUserRolesResponse
	(*RemoveRoleFromUserResponse)(nil),      // 61: apiserver.v1.RemoveRoleFromUserResponse
}
var file_apiserver_v1_apiserver_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.BlogService.Healthz:input_type -> google.protobuf.Empty
	1,  // 1: apiserver.v1.BlogService.Login:input_type -> apiserver.v1.LoginRequest
	2,  // 2: apiserver.v1.BlogService.RefreshToken:input_type -> apiserver.v1.RefreshTokenRequest
	3,  // 3: apiserver.v1.BlogService.CreateUser:input_type -> apiserver.v1.CreateUserRequest
	4,  // 4: apiserver.v1.BlogService.GetUser:input_type -> apiserver.v1.GetUserRequest
	5,  // 5: apiserver.v1.BlogService.UpdateUser:input_type -> apiserver.v1.UpdateUserRequest
	6,  // 6: apiserver.v1.BlogService.DeleteUser:input_type -> apiserver.v1.DeleteUserRequest
	7,  // 7: apiserver.v1.BlogService.ListUsers:input_type -> apiserver.v1.ListUserRequest
	8,  // 8: apiserver.v1.BlogService.CreateMenu:input_type -> apiserver.v1.CreateMenuRequest
	9,  // 9: apiserver.v1.BlogService.GetMenu:input_type -> apiserver.v1.GetMenuRequest
	10, // 10: apiserver.v1.BlogService.UpdateMenu:input_type -> apiserver.v1.UpdateMenuRequest
	11, // 11: apiserver.v1.BlogService.DeleteMenu:input_type -> apiserver.v1.DeleteMenuRequest
	12, // 12: apiserver.v1.BlogService.ListMenus:input_type -> apiserver.v1.ListMenuRequest
	13, // 13: apiserver.v1.BlogService.ListMenuTree:input_type -> apiserver.v1.ListMenuTreeRequest
	14, // 14: apiserver.v1.BlogService.GetUserMenuTree:input_type -> apiserver.v1.GetUserMenuTreeRequest
	15, // 15: apiserver.v1.BlogService.CreatePermission:input_type -> apiserver.v1.CreatePermissionRequest
	16, // 16: apiserver.v1.BlogService.GetPermission:input_type -> apiserver.v1.GetPermissionRequest
	17, // 17: apiserver.v1.BlogService.UpdatePermission:input_type -> apiserver.v1.UpdatePermissionRequest
	18, // 18: apiserver.v1.BlogService.DeletePermission:input_type -> apiserver.v1.DeletePermissionRequest
	19, // 19: apiserver.v1.BlogService.ListPermissions:input_type -> apiserver.v1.ListPermissionRequest
	20, // 20: apiserver.v1.BlogService.ListPermissionTree:input_type -> apiserver.v1.ListPermissionTreeRequest
	21, // 21: apiserver.v1.BlogService.CreateRole:input_type -> apiserver.v1.CreateRoleRequest
	22, // 22: apiserver.v1.BlogService.GetRole:input_type -> apiserver.v1.GetRoleRequest
	23, // 23: apiserver.v1.BlogService.UpdateRole:input_type -> apiserver.v1.UpdateRoleRequest
	24, // 24: apiserver.v1.BlogService.DeleteRole:input_type -> apiserver.v1.DeleteRoleRequest
	25, // 25: apiserver.v1.BlogService.ListRoles:input_type -> apiserver.v1.ListRoleRequest
	26, // 26: apiserver.v1.BlogService.AssignPermissionsToRole:input_type -> apiserver.v1.AssignPermissionsToRoleRequest
	27, // 27: apiserver.v1.BlogService.GetRolePermissions:input_type -> apiserver.v1.GetRolePermissionsRequest
	28, // 28: apiserver.v1.BlogService.AssignRolesToUser:input_type -> apiserver.v1.AssignRolesToUserRequest
	29, // 29: apiserver.v1.BlogService.GetUserRoles:input_type -> apiserver.v1.GetUserRolesRequest
	30, // 30: apiserver.v1.BlogService.RemoveRoleFromUser:input_type -> apiserver.v1.RemoveRoleFromUserRequest
	31, // 31: apiserver.v1.BlogService.Healthz:output_type -> apiserver.v1.HealthzResponse
	32, // 32: apiserver.v1.BlogService.Login:output_type -> apiserver.v1.LoginResponse
	33, // 33: apiserver.v1.BlogService.RefreshToken:output_type -> apiserver.v1.RefreshTokenResponse
	34, // 34: apiserver.v1.BlogService.CreateUser:output_type -> apiserver.v1.CreateUserResponse
	35, // 35: apiserver.v1.BlogService.GetUser:output_type -> apiserver.v1.GetUserResponse
	36, // 36: apiserver.v1.BlogService.UpdateUser:output_type -> apiserver.v1.UpdateUserResponse
	37, // 37: apiserver.v1.BlogService.DeleteUser:output_type -> apiserver.v1.DeleteUserResponse
	38, // 38: apiserver.v1.BlogService.ListUsers:output_type -> apiserver.v1.ListUserResponse
	39, // 39: apiserver.v1.BlogService.CreateMenu:output_type -> apiserver.v1.CreateMenuResponse
	40, // 40: apiserver.v1.BlogService.GetMenu:output_type -> apiserver.v1.GetMenuResponse
	41, // 41: apiserver.v1.BlogService.UpdateMenu:output_type -> apiserver.v1.UpdateMenuResponse
	42, // 42: apiserver.v1.BlogService.DeleteMenu:output_type -> apiserver.v1.DeleteMenuResponse
	43, // 43: apiserver.v1.BlogService.ListMenus:output_type -> apiserver.v1.ListMenuResponse
	44, // 44: apiserver.v1.BlogService.ListMenuTree:output_type -> apiserver.v1.ListMenuTreeResponse
	45, // 45: apiserver.v1.BlogService.GetUserMenuTree:output_type -> apiserver.v1.GetUserMenuTreeResponse
	46, // 46: apiserver.v1.BlogService.CreatePermission:output_type -> apiserver.v1.CreatePermissionResponse
	47, // 47: apiserver.v1.BlogService.GetPermission:output_type -> apiserver.v1.GetPermissionResponse
	48, // 48: apiserver.v1.BlogService.UpdatePermission:output_type -> apiserver.v1.UpdatePermissionResponse
	49, // 49: apiserver.v1.BlogService.DeletePermission:output_type -> apiserver.v1.DeletePermissionResponse
	50, // 50: apiserver.v1.BlogService.ListPermissions:output_type -> apiserver.v1.ListPermissionResponse
	51, // 51: apiserver.v1.BlogService.ListPermissionTree:output_type -> apiserver.v1.ListPermissionTreeResponse
	52, // 52: apiserver.v1.BlogService.CreateRole:output_type -> apiserver.v1.CreateRoleResponse
	53, // 53: apiserver.v1.BlogService.GetRole:output_type -> apiserver.v1.GetRoleResponse
	54, // 54: apiserver.v1.BlogService.UpdateRole:output_type -> apiserver.v1.UpdateRoleResponse
	55, // 55: apiserver.v1.BlogService.DeleteRole:output_type -> apiserver.v1.DeleteRoleResponse
	56, // 56: apiserver.v1.BlogService.ListRoles:output_type -> apiserver.v1.ListRoleResponse
	57, // 57: apiserver.v1.BlogService.AssignPermissionsToRole:output_type -> apiserver.v1.AssignPermissionsToRoleResponse
	58, // 58: apiserver.v1.BlogService.GetRolePermissions:output_type -> apiserver.v1.GetRolePermissionsResponse
	59, // 59: apiserver.v1.BlogService.AssignRolesToUser:output_type -> apiserver.v1.AssignRolesToUserResponse
	60, // 60: apiserver.v1.BlogService.GetUserRoles:output_type -> apiserver.v1.GetUserRolesResponse
	61, // 61: apiserver.v1.BlogService.RemoveRoleFromUser:output_type -> apiserver.v1.RemoveRoleFromUserResponse
	31, // [31:62] is the sub-list for method output_type
	0,  // [0:31] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_apiserver_proto_init() }
func file_apiserver_v1_apiserver_proto_init() {
	if File_apiserver_v1_apiserver_proto != nil {
		return
	}
	file_apiserver_v1_healthz_proto_init()
	file_apiserver_v1_user_proto_init()
	file_apiserver_v1_menu_proto_init()
	file_apiserver_v1_permission_proto_init()
	file_apiserver_v1_role_proto_init()
	file_apiserver_v1_user_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_apiserver_proto_rawDesc), len(file_apiserver_v1_apiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_v1_apiserver_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_apiserver_proto_depIdxs,
	}.Build()
	File_apiserver_v1_apiserver_proto = out.File
	file_apiserver_v1_apiserver_proto_goTypes = nil
	file_apiserver_v1_apiserver_proto_depIdxs = nil
}
